<?php

use Illuminate\Database\Seeder;

class PelangganTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pelanggan')->delete();
        
        \DB::table('pelanggan')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nama_pengguna_jasa' => 'Jasa Marga',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'Pemerintah',
                'email' => 'dudyiskandar325@gmail.com',
                'no_telp' => '12310',
                'contact_person' => 'QWERTY',
                'no_telp_cp' => '1231',
                'alamat' => 'Jauh Pake Helm',
                'negara' => 'Indonesia',
                'kecamatan' => 'Dramaga',
                'kelurahan' => 'Purwasari',
                'kode_pos' => 16680,
                'created_by' => 1,
                'created_at' => '2018-10-19 09:11:08',
                'updated_at' => '2018-10-19 09:13:04',
                'updated_by' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'nama_pengguna_jasa' => 'test',
                'kategori_pengguna_jasa_id' => 3,
                'divisi' => 'ok',
                'email' => 'ariespratama96@gmail.com',
                'no_telp' => '1287',
                'contact_person' => 'asdjk',
                'no_telp_cp' => '2831923',
                'alamat' => 'ok',
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 04:07:17',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            2 => 
            array (
                'id' => 9,
                'nama_pengguna_jasa' => 'test',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'ok',
                'email' => 'ariespratama96@gmail.co2',
                'no_telp' => '1287',
                'contact_person' => 'asdjk',
                'no_telp_cp' => '2831923',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 05:17:09',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            3 => 
            array (
                'id' => 10,
                'nama_pengguna_jasa' => 'Jasa Marga',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'Pemerintah',
                'email' => 'dudyiskandar325@gmail.com2',
                'no_telp' => '12310',
                'contact_person' => 'QWERTY',
                'no_telp_cp' => '1231',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 05:17:40',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            4 => 
            array (
                'id' => 24,
                'nama_pengguna_jasa' => 'test',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'ok',
                'email' => 'ariespratama96@gmail.com',
                'no_telp' => '1287',
                'contact_person' => 'asdjk',
                'no_telp_cp' => '2831923',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 08:00:27',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            5 => 
            array (
                'id' => 25,
                'nama_pengguna_jasa' => 'Jasa Marga',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'Pemerintah',
                'email' => 'dudyiskandar325@gmail.com',
                'no_telp' => '12310',
                'contact_person' => 'QWERTY',
                'no_telp_cp' => '1231',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 08:00:30',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            6 => 
            array (
                'id' => 26,
                'nama_pengguna_jasa' => 'test',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'ok',
                'email' => 'ariespratama96@gmail.com',
                'no_telp' => '1287',
                'contact_person' => 'asdjk',
                'no_telp_cp' => '2831923',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 08:09:35',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            7 => 
            array (
                'id' => 27,
                'nama_pengguna_jasa' => 'Jasa Marga',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'Pemerintah',
                'email' => 'dudyiskandar325@gmail.com',
                'no_telp' => '12310',
                'contact_person' => 'QWERTY',
                'no_telp_cp' => '1231',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 08:09:37',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            8 => 
            array (
                'id' => 28,
                'nama_pengguna_jasa' => 'test',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'ok',
                'email' => 'ariespratama96@gmail.com',
                'no_telp' => '1287',
                'contact_person' => 'asdjk',
                'no_telp_cp' => '2831923',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 08:11:04',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            9 => 
            array (
                'id' => 29,
                'nama_pengguna_jasa' => 'Jasa Marga',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'Pemerintah',
                'email' => 'dudyiskandar325@gmail.com',
                'no_telp' => '12310',
                'contact_person' => 'QWERTY',
                'no_telp_cp' => '1231',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 08:11:05',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            10 => 
            array (
                'id' => 30,
                'nama_pengguna_jasa' => 'test',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'ok',
                'email' => 'ariespratama96@gmail.com',
                'no_telp' => '1287',
                'contact_person' => 'asdjk',
                'no_telp_cp' => '2831923',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 08:13:57',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            11 => 
            array (
                'id' => 31,
                'nama_pengguna_jasa' => 'Jasa Marga',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'Pemerintah',
                'email' => 'dudyiskandar325@gmail.com',
                'no_telp' => '12310',
                'contact_person' => 'QWERTY',
                'no_telp_cp' => '1231',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-22 08:14:00',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
            12 => 
            array (
                'id' => 32,
                'nama_pengguna_jasa' => 'Jasa Marga',
                'kategori_pengguna_jasa_id' => 2,
                'divisi' => 'Pemerintah',
                'email' => 'dudyiskandar325@gmail.com',
                'no_telp' => '12310',
                'contact_person' => 'QWERTY',
                'no_telp_cp' => '1231',
                'alamat' => NULL,
                'negara' => NULL,
                'kecamatan' => NULL,
                'kelurahan' => NULL,
                'kode_pos' => NULL,
                'created_by' => 1,
                'created_at' => '2018-10-23 00:10:32',
                'updated_at' => NULL,
                'updated_by' => NULL,
            ),
        ));
        
        
    }
}